### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by di72nn**
Hi!
Recently I had an idea about using Device Admin API to implement this app's functionality and was pleasantly surprised to discover this app on F-Droid. Thanks for developing it!

Everything is in the commit messages, so not going to list all the changes here.

The "Lock now" feature calls [this method](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#lockNow()) that has the following description: "After this method is called, the device must be unlocked using strong authentication (PIN, pattern, or password)." This effectively disables fingerprint until first proper unlock (which covers cases like properly locking the screen when you go to sleep, but don't trust the environment).

It's the first time I touched quick setting tiles, so I'm not completely sure about the implementation (specifically the tile update in "active" mode). I'm currently testing it on my phone.

The last commit removes most of the IDEA/AndroidStudio stuff, because it's not worth keeping it in the repo. You can drop the commit if you disagree.

### CODE REVIEW

**Comment by linux-colonel** [comment]
awesome!  thanks for working on this.  I've been pretty busy lately so it might be a little while before I get a chance to test this, but I intend to test & merge.

**Comment by di72nn** [comment]
No problem, take your time.

Can I ask you to label this PR as `hacktoberfest-accepted`? (I didn't _mean_ it to be for [Hacktoberfest](https://hacktoberfest.digitalocean.com), but it's October already, so why not.)
The label doesn't affect the repo or mean that you need to do anything else.

**Comment by di72nn** [comment]
Today I learned about "Lockdown mode", which was introduced in Android 9. It seems to be doing something like [DevicePolicyManager.lockNow()](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#lockNow()) (or maybe even exactly the same). It needs to be enabled in settings and is usually available in the power button menu.

So the "lock now" feature in this PR may need to be renamed.

**Comment by linux-colonel** [comment]
Thanks again for the improvements!   I really like how the QuickSettings tile can hard-lock the device (no fingerprint) even from the lockscreen!  LineageOS really needs this feature; it's too many taps away in the power menu.

**Pull request merged**
